### ISSUE TITLE
automate the running of the linter

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#109]
@squashic and i were discussing the repeated accumulation of lint in the codebase (of which I myself am guilty of contributing to), and wondered if there was a low-cost way of automating the linting process so folks don't have to remember. 

We could make it part of the default `mix` task that kicks up when we run the server, but i fear the lint messages would get lost in the server output. Has anyone ever set this up to run on and fail builds on CircleCI? Please discuss!

**Comment by pulsedemon** [comment]
It's true that if we run the linter as part of the default `mix` task, the errors/warnings might get lost, but that would be the only way to make it fully automated.  What if we configured the linter to use some notification plugin similar to webpack-notifier?

**Comment by samdec11** [comment]
@vanderhoop I've seen linting included in test runners in the past. What if we just make it run at the end of the `mix test` command?

**Comment by tnewell5** [comment]
hey @vanderhoop did you have any more thoughts on this? should I try implementing Sean's idea above (making the linter run at the end of the 'mix test' command)?

**Comment by tnewell5** [comment]
per Travis: not at the moment


[3:07] 
the linter is pretty slow


[3:07] 
whereas `mix test` is really fast


[3:07] 
right now, there’s no lint


[3:08] 
so i feel like it’s less of a problem than it was at the time the issue was created


[3:08] 
what we could do is add it to the circle build


[3:08] 
so that the build fails if the linter returns a failure status


[3:09] 
i’d push back on that as a priority though

**Comment by vanderhoop** [comment]
closing this issue due to its atrophy and the consistently low levels of lint
