### ISSUE TITLE
Set deadline for having MVP

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#209]
As a contributor,
I would like to set a deadline for having an MVP that we would be proud to share widely,
So that leadership has more clarity on when Remote Retro will be ready to share with the world.

__By Way Of Explanation:__ Debbie would like us to commit to a deadline for having an MVP ready for Zach to market and publicize. We should discuss and agree to a deadline by July 31st evening so we can share the deadline with Debbie during Bench Demo + Planning on Aug 1.

__Acceptance Criteria:__

- [x] Deadline is agreed on

**Comment by vanderhoop** [comment]
hey @qlaire. i discussed deadlines briefly with Debbie, and while we didn't decide *not* to set a deadline, we did agree that we are already in a place where we can begin marketing in small (i.e. not big bang) ways, especially in seeking beta testers, which is the product's biggest need right now. 

When will the app be something that we issue a press release about? that's impossible to say, due to a number of variables (how many devs are working on it at any given time is likely to vary due to bench size) and how effective we are cutting scope.

**Comment by vanderhoop** [comment]
This story kinda of fell by the wayside, but we have an open beta, which we'll be publicizing just as soon as I finish the announcement blog post
