### ISSUE TITLE
implement retro index

### ISSUE THREAD

**Issue by williamcodes** [stride-nyc/remote_retro#345]
As a logged in user,
I want a dashboard for reviewing my previous retros,
So I can easily navigate to and review my previously attended retros.

__By Way of Explanation:__ retro links are unique, using each persisted retro's UUID in the path. This doesn't make returning to a particular retro easy, which is frustrating for users who want to review retros.

**Acceptance Criteria:**

- [x] when an authenticated user visits `/retros`, they are presented with a page containing a header that reads 'My Retros', 
- [x] if the user has participated in a retro before, the header is followed by with a bulleted list of links to any retros that they have participated in in the past
  - the list is ordered by retro creation descending
  - each list item is followed by its creation timestamp in a readable date format (held 4-14-2018)
- [x] if the user _hasn't_ participated in a retro before, the header is followed text that reads "You don't have any retros yet!"
- [x]  regardless of whether the user has ever taken part in a retro before, the list area is followed by the 'Create a Retrospective for Your Team' button that [currently resides on the `/` view](https://github.com/stride-nyc/remote_retro/blob/2d5f77d1332422eb15b205a82c5aa36500619747/web/templates/page/index.html.eex#L13-L18) when signed in.

__Product Note:__ while developing this feature, it will live at `/retros`, but it will not be linked to until a subsequent story.

__Helpful Links:__
- [Phoenix Views](https://hexdocs.pm/phoenix/views.html)
- [Phoenix Templates](https://hexdocs.pm/phoenix/templates.html)

**Comment by vanderhoop** [comment]
hey @williamcodes and @derekparham! this is a great idea. may take awhile to get to it, but i'll  groom it this week!

**Comment by vanderhoop** [comment]
@williamcodes @derekparham long term, setting up teams that have recurring retros and action item completion tracking and reminders would be great. so much to do 😄

**Comment by derekparham** [comment]
Great!  Happy to chat through the usecase more if needed

**Comment by nicholalexander** [comment]
hey @vanderhoop - i'd like to have a go at this if you need someone on it.  feel free to assign me if you wish!

n

**Comment by vanderhoop** [comment]
hey @derekparham + @williamcodes + @samdec11 + @dvndrsn + @kimberlysuazo + @caporta + @genegurvich + @madelynfreed! Joor people! We recently implemented a retro index page that a) includes links to a user's last 10 retros, and b) surfaces any action items associated with said retros. Our hope is that this makes action item review more front-and-center *before* entering the retro, but we'd love your feedback!

**Comment by derekparham** [comment]
@vanderhoop thanks!  I'd actually love a link to the full retro details including votes as well. Sometimes it's really nice to see the full swath of topics entered. With the votes, I can see topics that might have gotten a few votes but not talked about as well.

**Comment by vanderhoop** [comment]
Hey @derekparham! I hate to tell you this, as you've been such a great supporter of the project, but as RemoteRetro grows, we're likely to expose _less_ of a 'closed' retro's data rather than more. The reason for this is that--while I know that _your_ intentions are good, in organizations less healthy than Joor, managers and higher ups who get access to these retro links could use such a complete picture of the their team's retros as a sort of glory hole into what _should_ be a private, safe ritual. 

To that end, once the grouping stage has been implemented, the only data likely to be exposed in 'closed' retros are the groupings that were most-voted-upon, and any action items that were generated.

**Comment by vanderhoop** [comment]
__for posterity:__ I'm going to close this issue for now, but that doesn't mean that the discussion needs to stop!

**Comment by derekparham** [comment]
@vanderhoop You mentioned 'closed' retro.  Is there a way to turn a retro to 'open'?  It is a very strong need of mine to be able to see the results of retros as normally I'd be sitting in the room itself but I simply can't do that due to conflicts and sometimes they happen at the same time.

Totally hear the concern about privacy but I would instead lean on letting participants easily remove entries they thought were sensitive versus prevent all sharing.  For instance, it's useful for us to pull back up old teamwide retros from months ago and re-visit top items there to make sure we're making progress. Without it being saved, I have to take a screenshot and store that which is doable, just really annoying. @williamcodes
