### ISSUE TITLE
allow non-facilitators to delete a submitted idea within 5s of submission

### ISSUE THREAD

**Issue by williamcodes** [stride-nyc/remote_retro#35]
As a non-facilitator participant who has mistakenly added an idea to the board,
I would like to be able to delete that idea from the board,
So that I don't feel I have cluttered the board.

__Acceptance Criteria__
- [ ] non-facilitators see the delete button beside each of __their__ ideas
- [ ] after 5s have elapsed since the idea was persisted, the delete button fades out.
  - __Note:__ this was initially in story #53, which was written prior to the facilitator deletion story. The feeling is that we don't want to merge/deploy this deletion feature in an incomplete state, as ideas that have been on the board for 5s would allow folks to remove ideas that other participants have already taken in.
- [ ] when a non-facilitator deletes an idea they've submitted, all connected clients see the idea removed from their board.
- [ ] upon refreshing the page, the deleted item is not displayed

**Comment by vanderhoop** [comment]
hey @williamcodes, love that you went ahead and made this issue. One small piece of feedback on the format: ideally, all user stories are written such that they reveal the value to the user. For example, this story could be written as 

> As a retro participant who has mistakenly added an idea to the board,
I would like to be able to delete that idea from the board,
So that I don't feel I have cluttered the board

And then the specifics of the UI interactions and results could be shifted down to an Acceptance Criteria  list where you can get more granular.

**Comment by vanderhoop** [comment]
@williamcodes I realize you may have just fired this issue off to get it on the board, so sorry to nitpick in that case. I'm just happy you felt empowered to create it. Thanks!

**Comment by williamcodes** [comment]
@vanderhoop that's great feedback, thanks, updating the story

**Comment by Zanadar** [comment]
@vanderhoop Yo I wanna work on this one. Can I get added to the repo?

**Comment by vanderhoop** [comment]
@Zanadar yo! if and when you make a pull request for this guy, can you make it to the `feature/deleting-submitted-ideas` branch? I want to keep this off master until story #39, "disallow users from deleting other users' ideas", is complete, as it could introduce a weird intermediate state that could be off-putting to users. Thanks!
