### ISSUE TITLE
Optional feedback question disables feedback submission if no answer

### ISSUE THREAD

**Issue by dplain90** [stride-nyc/remote_retro#478]
As a user,
I want to be able to submit feedback without filling out the optional question:

> If no, what would it take to get your recommendation?

So that feedback can be accurately submitted for those that answer "yes" to using the product again.

__Acceptance Criteria:__
1. Feedback submit button is enabled on the _if no_ question regardless of whether or not text has been entered

I'm sure this just takes some settings tweaking within the retro hotjar account :)

**Comment by vanderhoop** [comment]
Hey @dplain90, thanks for submitting this! You're not the first person to mention it, but you _are_ the first person who took the trouble to create an issue, and that's immensely helpful, as this is an open source project rather than something we're working on full-time.

The hotjar settings have been updated so that folks finish the survey if they say Yes, and are only prompted for more granular feedback upon answering 'No'. Again, thanks!
