### ISSUE TITLE
investigate whether 'erl_child_setup closed' -> 'crash dump written' are normal as part of a gigalixir deploy

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#492]
We occasionally see the following sequence in the logs, usually--but not always--after restarting the phoenix server. It's possible this is a libcluster issue? I'll look into it, but possibly @jesseshieh might be familiar with this issue?

```
Sep 13 09:46:35 d.d9ea686c-5403-49ab-811a-81f043cc7cd5 remote-retro/remote-retro-1091501534-5lc5x:  web.1  | erl_child_setup closed 
Sep 13 09:46:35 d.d9ea686c-5403-49ab-811a-81f043cc7cd5 remote-retro/remote-retro-1091501534-5lc5x:  web.1  |  
Sep 13 09:46:36 d.d9ea686c-5403-49ab-811a-81f043cc7cd5 remote-retro/remote-retro-1091501534-5lc5x:  web.1  | Crash dump is being written to: erl_crash.dump...done 
Sep 13 09:46:36 d.d9ea686c-5403-49ab-811a-81f043cc7cd5 remote-retro/remote-retro-1091501534-5lc5x:  web.1  | exited with code 1 
Sep 13 09:46:36 d.d9ea686c-5403-49ab-811a-81f043cc7cd5 remote-retro/remote-retro-1091501534-5lc5x:  system | sending SIGTERM to all processes 
```

**Comment by jesseshieh** [comment]
I think more investigation is needed to find out why the app is crashing, but as a first step, I would check `gigalixir ps` or `gigalixir status` to see if anything stands out. Often when I see this, it is because of OOMKilled or out of memory errors. If that's the case, you can scale up with `gigalixir scale --size=1`

**Comment by vanderhoop** [comment]
addressed via @jesseshieh's comment above :)
