### ISSUE TITLE
Add unsubscribe option to email.

### ISSUE THREAD

**Issue by gcymbalski** [stride-nyc/remote_retro#562]
I've absolutely gotten more than enough marketing spam during this pandemic, and I do not appreciate that somebody thought this was a great time to gin up customers.

Add an 'unsubscribe' link to your email. Otherwise, lots of people like me are just going to mark it as spam and slowly lower your email sending reputation, and I suspect that won't be great for your business.

**Comment by vanderhoop** [comment]
Hey @gcymbalski, to address this we've added an explicit opt-in to non-transactional emails (defaulting to `false`), and will be sending emails anyone who opts in using unsubscribe features (i.e. via campaign instead of single-send emails). Sorry for the inconvenience, and thank you for taking time to write up this issue. 

![image](https://user-images.githubusercontent.com/4386645/83332819-9479fb80-a25a-11ea-9fc7-d4e939ff390c.png)
