### ISSUE TITLE
E2E specs + wifi issues

### ISSUE THREAD

**Issue by Zanadar** [stride-nyc/remote_retro#74]
When Wifi is off, I observe two things:
- Running e2e specs is significantly faster (18 second vs 4 second reported in logs).
- Test failures are different.  In the case of WiFi being on, I get
`** (Wallaby.QueryError) Expected to find 1, visible element that matched the css '.sad.ideas' but 0, visible elements were found.`
With WIFI off I get:
`  Expected false or nil, got true`

This may be a wallaby bug, but I think the timing has something to do with auth going out to the internet where it doesn't need to?

**Comment by vanderhoop** [comment]
hey @Zanadar I think this is owed to [the call for Semantic UI, which is hosted on a CDN](https://github.com/vanderhoop/remote_retro/blob/59db05708c1df9ab8efdd93b67084fc815f4ea26/web/templates/layout/app.html.eex#L11) (cloudflare). I had a commit that, but had to revert it due to it calling on relative paths for some icons

**Comment by Zanadar** [comment]
Gonna close this as a wontfix

**Comment by vanderhoop** [comment]
removed won't fix and reopening this, as it's a real issue for devs without a network connection

**Comment by vanderhoop** [comment]
handled by [this commit](https://github.com/stride-nyc/remote_retro/commit/165001986f217c8c7cd1e3e3280d4541fd458d9f)
